import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
<<<<<<< HEAD
import Hero from "../components/hero/Hero";
=======
import { useContext } from "react";
import TextImage from "../components/TextImage.js";
>>>>>>> 09a0cac02eca0052d9c0e56355ab9d9ba63aea86

export default function Home() {
  const content = {
    title: "Are you an online educator?",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    subTitle: "sub title for you",
    subDescription:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    imageUrl:
      "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1469&q=80",
    imageAltText: "Volkswagen",
  };

  const styles = {
    card: {
      background: "#dddddd",
      display: "flex",
      flexDirection: "row",
      width: 900,
      margin: "0 auto",
    },
    box: {
      display: "flex",
      flexDirection: "column",
    },
    cardContent: {
      flex: "1 0 auto",
    },
    cardMedia: {
      width: 350,
    },
    cardTitle: {
      fontSize: 30,
    },
    subTitle: {
      fontSize: 40,
    },
    subDescription: {
      // color: "green",
    },
    media: {
      width: "50%",
    },
  };

  return (
<<<<<<< HEAD
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <Hero />
        {/* <h1 className={styles.title}>Welcome to YouDemy!</h1> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
=======
    <>
      <div className="center">
        <h2>Home Page</h2>
      </div>
      <TextImage content={content} styles={styles} />
      <TextImage content={content} styles={styles} />
    </>
>>>>>>> 09a0cac02eca0052d9c0e56355ab9d9ba63aea86
  );
}
